//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceRangeSelector
    {
        public int RangeID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<int> ParameterID { get; set; }
        public Nullable<double> MinRange { get; set; }
        public Nullable<double> MaxRange { get; set; }
        public int CompanyID { get; set; }
    
        public virtual tblResource tblResource { get; set; }
    }
}
